#!/bin/sh
################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2012 Stephan Raue (stephan@openelec.tv)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.tv; see the file COPYING.  If not, write to
#  the Free Software Foundation, 51 Franklin Street, Suite 500, Boston, MA 02110, USA.
#  http://www.gnu.org/copyleft/gpl.html
################################################################################

PKG_NAME="szap-s2"
PKG_REPO="https://bitbucket.org/CrazyCat/szap-s2"

echo "getting sources..."
  if [ ! -d $PKG_NAME.hg ]; then
    hg clone  $PKG_REPO $PKG_NAME.hg
  fi

  cd $PKG_NAME.hg
    hg pull
    HG_REV=`hg identify --id`
  cd ..

echo "copying sources..."
  rm -rf $PKG_NAME-$HG_REV
  cp -R $PKG_NAME.hg $PKG_NAME-$HG_REV

echo "cleaning sources..."
  rm -rf $PKG_NAME-$HG_REV/.hg

echo "packing sources..."
  tar cvJf $PKG_NAME-$HG_REV.tar.xz $PKG_NAME-$HG_REV

echo "remove temporary sourcedir..."
  rm -rf $PKG_NAME-$HG_REV
