#!/bin/sh

################################################################################
#      This file is part of OpenELEC - http://www.openelec.tv
#      Copyright (C) 2009-2012 Stephan Raue (stephan@openelec.tv)
#
#  This Program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2, or (at your option)
#  any later version.
#
#  This Program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#
#  You should have received a copy of the GNU General Public License
#  along with OpenELEC.tv; see the file COPYING.  If not, write to
#  the Free Software Foundation, 51 Franklin Street, Suite 500, Boston, MA 02110, USA.
#  http://www.gnu.org/copyleft/gpl.html
################################################################################

PKG_NAME="oscam"
PKG_REPO="http://www.streamboard.tv/svn/oscam/trunk"

echo "getting sources..."
  svn checkout $PKG_REPO $PKG_NAME.svn

echo "getting version..."
  cd $PKG_NAME.svn
  #svn update -r 9842
    SVN_REV=`LANG=C svn info 2>/dev/null | grep Revision: | sed -e 's/.*\: //'`
    echo $SVN_REV
  cd ..

echo "copying sources..."
  rm -rf $PKG_NAME-$SVN_REV
  cp -R $PKG_NAME.svn $PKG_NAME-$SVN_REV

echo "packing sources..."
  tar cvJf $PKG_NAME-$SVN_REV.tar.xz $PKG_NAME-$SVN_REV

echo "remove temporary sourcedir..."
  rm -rf $PKG_NAME-$SVN_REV
